// <auto-generated />
using BrazilianFootballLeague.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrazilianFootballLeague.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200508193225_Data")]
    partial class Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Série A"
                        });
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions_ResultTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SeasonID");

                    b.HasIndex("TeamID");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Drawn = 9,
                            GoalsAgainst = 31,
                            GoalsFor = 71,
                            Lost = 5,
                            Played = 38,
                            Points = 81,
                            Position = 1,
                            SeasonID = 1,
                            TeamID = 10,
                            Won = 24
                        },
                        new
                        {
                            ID = 2,
                            Drawn = 6,
                            GoalsAgainst = 47,
                            GoalsFor = 65,
                            Lost = 11,
                            Played = 38,
                            Points = 69,
                            Position = 2,
                            SeasonID = 1,
                            TeamID = 3,
                            Won = 21
                        },
                        new
                        {
                            ID = 3,
                            Drawn = 8,
                            GoalsAgainst = 32,
                            GoalsFor = 52,
                            Lost = 10,
                            Played = 38,
                            Points = 68,
                            Position = 3,
                            SeasonID = 1,
                            TeamID = 19,
                            Won = 20
                        },
                        new
                        {
                            ID = 4,
                            Drawn = 8,
                            GoalsAgainst = 32,
                            GoalsFor = 52,
                            Lost = 10,
                            Played = 38,
                            Points = 68,
                            Position = 4,
                            SeasonID = 1,
                            TeamID = 27,
                            Won = 20
                        },
                        new
                        {
                            ID = 5,
                            Drawn = 9,
                            GoalsAgainst = 38,
                            GoalsFor = 39,
                            Lost = 12,
                            Played = 38,
                            Points = 60,
                            Position = 5,
                            SeasonID = 1,
                            TeamID = 20,
                            Won = 17
                        },
                        new
                        {
                            ID = 6,
                            Drawn = 14,
                            GoalsAgainst = 38,
                            GoalsFor = 53,
                            Lost = 9,
                            Played = 38,
                            Points = 59,
                            Position = 6,
                            SeasonID = 1,
                            TeamID = 28,
                            Won = 15
                        },
                        new
                        {
                            ID = 7,
                            Drawn = 10,
                            GoalsAgainst = 41,
                            GoalsFor = 59,
                            Lost = 12,
                            Played = 38,
                            Points = 58,
                            Position = 7,
                            SeasonID = 1,
                            TeamID = 26,
                            Won = 16
                        },
                        new
                        {
                            ID = 8,
                            Drawn = 10,
                            GoalsAgainst = 35,
                            GoalsFor = 44,
                            Lost = 13,
                            Played = 38,
                            Points = 55,
                            Position = 8,
                            SeasonID = 1,
                            TeamID = 12,
                            Won = 15
                        },
                        new
                        {
                            ID = 9,
                            Drawn = 8,
                            GoalsAgainst = 51,
                            GoalsFor = 60,
                            Lost = 15,
                            Played = 38,
                            Points = 53,
                            Position = 9,
                            SeasonID = 1,
                            TeamID = 22,
                            Won = 15
                        },
                        new
                        {
                            ID = 10,
                            Drawn = 9,
                            GoalsAgainst = 48,
                            GoalsFor = 43,
                            Lost = 15,
                            Played = 38,
                            Points = 51,
                            Position = 10,
                            SeasonID = 1,
                            TeamID = 4,
                            Won = 14
                        },
                        new
                        {
                            ID = 11,
                            Drawn = 12,
                            GoalsAgainst = 40,
                            GoalsFor = 41,
                            Lost = 13,
                            Played = 38,
                            Points = 51,
                            Position = 11,
                            SeasonID = 1,
                            TeamID = 24,
                            Won = 13
                        },
                        new
                        {
                            ID = 12,
                            Drawn = 4,
                            GoalsAgainst = 53,
                            GoalsFor = 45,
                            Lost = 19,
                            Played = 38,
                            Points = 49,
                            Position = 12,
                            SeasonID = 1,
                            TeamID = 15,
                            Won = 15
                        },
                        new
                        {
                            ID = 13,
                            Drawn = 5,
                            GoalsAgainst = 49,
                            GoalsFor = 40,
                            Lost = 19,
                            Played = 38,
                            Points = 47,
                            Position = 13,
                            SeasonID = 1,
                            TeamID = 16,
                            Won = 14
                        },
                        new
                        {
                            ID = 14,
                            Drawn = 11,
                            GoalsAgainst = 44,
                            GoalsFor = 34,
                            Lost = 15,
                            Played = 38,
                            Points = 47,
                            Position = 14,
                            SeasonID = 1,
                            TeamID = 9,
                            Won = 12
                        },
                        new
                        {
                            ID = 15,
                            Drawn = 11,
                            GoalsAgainst = 42,
                            GoalsFor = 31,
                            Lost = 16,
                            Played = 38,
                            Points = 44,
                            Position = 15,
                            SeasonID = 1,
                            TeamID = 11,
                            Won = 11
                        },
                        new
                        {
                            ID = 16,
                            Drawn = 10,
                            GoalsAgainst = 50,
                            GoalsFor = 36,
                            Lost = 17,
                            Played = 38,
                            Points = 43,
                            Position = 16,
                            SeasonID = 1,
                            TeamID = 14,
                            Won = 11
                        },
                        new
                        {
                            ID = 17,
                            Drawn = 9,
                            GoalsAgainst = 60,
                            GoalsFor = 38,
                            Lost = 18,
                            Played = 38,
                            Points = 42,
                            Position = 17,
                            SeasonID = 1,
                            TeamID = 5,
                            Won = 11
                        },
                        new
                        {
                            ID = 18,
                            Drawn = 11,
                            GoalsAgainst = 54,
                            GoalsFor = 28,
                            Lost = 17,
                            Played = 38,
                            Points = 41,
                            Position = 18,
                            SeasonID = 1,
                            TeamID = 29,
                            Won = 10
                        },
                        new
                        {
                            ID = 19,
                            Drawn = 8,
                            GoalsAgainst = 49,
                            GoalsFor = 39,
                            Lost = 20,
                            Played = 38,
                            Points = 38,
                            Position = 19,
                            SeasonID = 1,
                            TeamID = 18,
                            Won = 10
                        },
                        new
                        {
                            ID = 20,
                            Drawn = 10,
                            GoalsAgainst = 48,
                            GoalsFor = 26,
                            Lost = 21,
                            Played = 38,
                            Points = 31,
                            Position = 20,
                            SeasonID = 1,
                            TeamID = 21,
                            Won = 7
                        },
                        new
                        {
                            ID = 21,
                            Drawn = 8,
                            GoalsAgainst = 32,
                            GoalsFor = 62,
                            Lost = 6,
                            Played = 38,
                            Points = 80,
                            Position = 1,
                            SeasonID = 2,
                            TeamID = 22,
                            Won = 24
                        },
                        new
                        {
                            ID = 22,
                            Drawn = 5,
                            GoalsAgainst = 35,
                            GoalsFor = 59,
                            Lost = 11,
                            Played = 38,
                            Points = 71,
                            Position = 2,
                            SeasonID = 2,
                            TeamID = 26,
                            Won = 22
                        },
                        new
                        {
                            ID = 23,
                            Drawn = 11,
                            GoalsAgainst = 35,
                            GoalsFor = 52,
                            Lost = 7,
                            Played = 38,
                            Points = 71,
                            Position = 3,
                            SeasonID = 2,
                            TeamID = 15,
                            Won = 20
                        },
                        new
                        {
                            ID = 24,
                            Drawn = 11,
                            GoalsAgainst = 53,
                            GoalsFor = 61,
                            Lost = 10,
                            Played = 38,
                            Points = 62,
                            Position = 4,
                            SeasonID = 2,
                            TeamID = 3,
                            Won = 17
                        },
                        new
                        {
                            ID = 25,
                            Drawn = 8,
                            GoalsAgainst = 39,
                            GoalsFor = 43,
                            Lost = 13,
                            Played = 38,
                            Points = 59,
                            Position = 5,
                            SeasonID = 2,
                            TeamID = 7,
                            Won = 17
                        },
                        new
                        {
                            ID = 26,
                            Drawn = 6,
                            GoalsAgainst = 32,
                            GoalsFor = 38,
                            Lost = 15,
                            Played = 38,
                            Points = 57,
                            Position = 6,
                            SeasonID = 2,
                            TeamID = 4,
                            Won = 17
                        },
                        new
                        {
                            ID = 27,
                            Drawn = 10,
                            GoalsAgainst = 42,
                            GoalsFor = 48,
                            Lost = 13,
                            Played = 38,
                            Points = 55,
                            Position = 7,
                            SeasonID = 2,
                            TeamID = 10,
                            Won = 15
                        },
                        new
                        {
                            ID = 28,
                            Drawn = 8,
                            GoalsAgainst = 52,
                            GoalsFor = 48,
                            Lost = 15,
                            Played = 38,
                            Points = 53,
                            Position = 8,
                            SeasonID = 2,
                            TeamID = 24,
                            Won = 15
                        },
                        new
                        {
                            ID = 29,
                            Drawn = 11,
                            GoalsAgainst = 44,
                            GoalsFor = 41,
                            Lost = 13,
                            Played = 38,
                            Points = 53,
                            Position = 9,
                            SeasonID = 2,
                            TeamID = 19,
                            Won = 14
                        },
                        new
                        {
                            ID = 30,
                            Drawn = 10,
                            GoalsAgainst = 36,
                            GoalsFor = 44,
                            Lost = 14,
                            Played = 38,
                            Points = 52,
                            Position = 10,
                            SeasonID = 2,
                            TeamID = 27,
                            Won = 14
                        },
                        new
                        {
                            ID = 31,
                            Drawn = 13,
                            GoalsAgainst = 56,
                            GoalsFor = 49,
                            Lost = 12,
                            Played = 38,
                            Points = 52,
                            Position = 11,
                            SeasonID = 2,
                            TeamID = 9,
                            Won = 13
                        },
                        new
                        {
                            ID = 32,
                            Drawn = 9,
                            GoalsAgainst = 49,
                            GoalsFor = 48,
                            Lost = 15,
                            Played = 38,
                            Points = 51,
                            Position = 12,
                            SeasonID = 2,
                            TeamID = 12,
                            Won = 14
                        },
                        new
                        {
                            ID = 33,
                            Drawn = 11,
                            GoalsAgainst = 45,
                            GoalsFor = 45,
                            Lost = 14,
                            Played = 38,
                            Points = 50,
                            Position = 13,
                            SeasonID = 2,
                            TeamID = 16,
                            Won = 13
                        },
                        new
                        {
                            ID = 34,
                            Drawn = 8,
                            GoalsAgainst = 55,
                            GoalsFor = 49,
                            Lost = 17,
                            Played = 38,
                            Points = 47,
                            Position = 14,
                            SeasonID = 2,
                            TeamID = 28,
                            Won = 13
                        },
                        new
                        {
                            ID = 35,
                            Drawn = 13,
                            GoalsAgainst = 42,
                            GoalsFor = 41,
                            Lost = 14,
                            Played = 38,
                            Points = 46,
                            Position = 15,
                            SeasonID = 2,
                            TeamID = 11,
                            Won = 11
                        },
                        new
                        {
                            ID = 36,
                            Drawn = 9,
                            GoalsAgainst = 53,
                            GoalsFor = 51,
                            Lost = 17,
                            Played = 38,
                            Points = 45,
                            Position = 16,
                            SeasonID = 2,
                            TeamID = 30,
                            Won = 12
                        },
                        new
                        {
                            ID = 37,
                            Drawn = 10,
                            GoalsAgainst = 41,
                            GoalsFor = 35,
                            Lost = 17,
                            Played = 38,
                            Points = 43,
                            Position = 17,
                            SeasonID = 2,
                            TeamID = 20,
                            Won = 11
                        },
                        new
                        {
                            ID = 38,
                            Drawn = 13,
                            GoalsAgainst = 50,
                            GoalsFor = 30,
                            Lost = 17,
                            Played = 38,
                            Points = 37,
                            Position = 18,
                            SeasonID = 2,
                            TeamID = 14,
                            Won = 8
                        },
                        new
                        {
                            ID = 39,
                            Drawn = 7,
                            GoalsAgainst = 69,
                            GoalsFor = 45,
                            Lost = 23,
                            Played = 38,
                            Points = 28,
                            Position = 19,
                            SeasonID = 2,
                            TeamID = 25,
                            Won = 8
                        },
                        new
                        {
                            ID = 40,
                            Drawn = 7,
                            GoalsAgainst = 58,
                            GoalsFor = 23,
                            Lost = 24,
                            Played = 38,
                            Points = 28,
                            Position = 20,
                            SeasonID = 2,
                            TeamID = 1,
                            Won = 7
                        },
                        new
                        {
                            ID = 41,
                            Drawn = 9,
                            GoalsAgainst = 30,
                            GoalsFor = 50,
                            Lost = 8,
                            Played = 38,
                            Points = 72,
                            Position = 1,
                            SeasonID = 3,
                            TeamID = 10,
                            Won = 21
                        },
                        new
                        {
                            ID = 42,
                            Drawn = 6,
                            GoalsAgainst = 45,
                            GoalsFor = 61,
                            Lost = 13,
                            Played = 38,
                            Points = 63,
                            Position = 2,
                            SeasonID = 3,
                            TeamID = 22,
                            Won = 19
                        },
                        new
                        {
                            ID = 43,
                            Drawn = 12,
                            GoalsAgainst = 32,
                            GoalsFor = 42,
                            Lost = 9,
                            Played = 38,
                            Points = 63,
                            Position = 3,
                            SeasonID = 3,
                            TeamID = 26,
                            Won = 17
                        },
                        new
                        {
                            ID = 44,
                            Drawn = 8,
                            GoalsAgainst = 36,
                            GoalsFor = 55,
                            Lost = 12,
                            Played = 38,
                            Points = 62,
                            Position = 4,
                            SeasonID = 3,
                            TeamID = 19,
                            Won = 18
                        },
                        new
                        {
                            ID = 45,
                            Drawn = 12,
                            GoalsAgainst = 39,
                            GoalsFor = 47,
                            Lost = 11,
                            Played = 38,
                            Points = 57,
                            Position = 5,
                            SeasonID = 3,
                            TeamID = 12,
                            Won = 15
                        },
                        new
                        {
                            ID = 46,
                            Drawn = 11,
                            GoalsAgainst = 38,
                            GoalsFor = 49,
                            Lost = 12,
                            Played = 38,
                            Points = 56,
                            Position = 6,
                            SeasonID = 3,
                            TeamID = 15,
                            Won = 15
                        },
                        new
                        {
                            ID = 47,
                            Drawn = 11,
                            GoalsAgainst = 47,
                            GoalsFor = 40,
                            Lost = 12,
                            Played = 38,
                            Points = 56,
                            Position = 7,
                            SeasonID = 3,
                            TeamID = 29,
                            Won = 15
                        },
                        new
                        {
                            ID = 48,
                            Drawn = 9,
                            GoalsAgainst = 49,
                            GoalsFor = 47,
                            Lost = 14,
                            Played = 38,
                            Points = 54,
                            Position = 8,
                            SeasonID = 3,
                            TeamID = 9,
                            Won = 15
                        },
                        new
                        {
                            ID = 49,
                            Drawn = 12,
                            GoalsAgainst = 49,
                            GoalsFor = 52,
                            Lost = 12,
                            Played = 38,
                            Points = 54,
                            Position = 9,
                            SeasonID = 3,
                            TeamID = 3,
                            Won = 14
                        },
                        new
                        {
                            ID = 50,
                            Drawn = 11,
                            GoalsAgainst = 42,
                            GoalsFor = 45,
                            Lost = 13,
                            Played = 38,
                            Points = 53,
                            Position = 10,
                            SeasonID = 3,
                            TeamID = 7,
                            Won = 14
                        },
                        new
                        {
                            ID = 51,
                            Drawn = 9,
                            GoalsAgainst = 43,
                            GoalsFor = 45,
                            Lost = 15,
                            Played = 38,
                            Points = 51,
                            Position = 11,
                            SeasonID = 3,
                            TeamID = 4,
                            Won = 14
                        },
                        new
                        {
                            ID = 52,
                            Drawn = 11,
                            GoalsAgainst = 48,
                            GoalsFor = 50,
                            Lost = 14,
                            Played = 38,
                            Points = 50,
                            Position = 12,
                            SeasonID = 3,
                            TeamID = 6,
                            Won = 13
                        },
                        new
                        {
                            ID = 53,
                            Drawn = 11,
                            GoalsAgainst = 49,
                            GoalsFor = 48,
                            Lost = 14,
                            Played = 38,
                            Points = 50,
                            Position = 13,
                            SeasonID = 3,
                            TeamID = 27,
                            Won = 13
                        },
                        new
                        {
                            ID = 54,
                            Drawn = 14,
                            GoalsAgainst = 53,
                            GoalsFor = 50,
                            Lost = 13,
                            Played = 38,
                            Points = 47,
                            Position = 14,
                            SeasonID = 3,
                            TeamID = 16,
                            Won = 11
                        },
                        new
                        {
                            ID = 55,
                            Drawn = 9,
                            GoalsAgainst = 58,
                            GoalsFor = 46,
                            Lost = 17,
                            Played = 38,
                            Points = 45,
                            Position = 15,
                            SeasonID = 3,
                            TeamID = 28,
                            Won = 12
                        },
                        new
                        {
                            ID = 56,
                            Drawn = 10,
                            GoalsAgainst = 58,
                            GoalsFor = 50,
                            Lost = 17,
                            Played = 38,
                            Points = 43,
                            Position = 16,
                            SeasonID = 3,
                            TeamID = 30,
                            Won = 11
                        },
                        new
                        {
                            ID = 57,
                            Drawn = 10,
                            GoalsAgainst = 51,
                            GoalsFor = 42,
                            Lost = 17,
                            Played = 38,
                            Points = 43,
                            Position = 17,
                            SeasonID = 3,
                            TeamID = 11,
                            Won = 11
                        },
                        new
                        {
                            ID = 58,
                            Drawn = 13,
                            GoalsAgainst = 48,
                            GoalsFor = 29,
                            Lost = 15,
                            Played = 38,
                            Points = 43,
                            Position = 18,
                            SeasonID = 3,
                            TeamID = 5,
                            Won = 10
                        },
                        new
                        {
                            ID = 59,
                            Drawn = 9,
                            GoalsAgainst = 52,
                            GoalsFor = 37,
                            Lost = 19,
                            Played = 38,
                            Points = 39,
                            Position = 19,
                            SeasonID = 3,
                            TeamID = 24,
                            Won = 10
                        },
                        new
                        {
                            ID = 60,
                            Drawn = 9,
                            GoalsAgainst = 56,
                            GoalsFor = 38,
                            Lost = 20,
                            Played = 38,
                            Points = 36,
                            Position = 20,
                            SeasonID = 3,
                            TeamID = 2,
                            Won = 9
                        },
                        new
                        {
                            ID = 61,
                            Drawn = 11,
                            GoalsAgainst = 26,
                            GoalsFor = 64,
                            Lost = 4,
                            Played = 38,
                            Points = 80,
                            Position = 1,
                            SeasonID = 4,
                            TeamID = 22,
                            Won = 23
                        },
                        new
                        {
                            ID = 62,
                            Drawn = 9,
                            GoalsAgainst = 29,
                            GoalsFor = 59,
                            Lost = 8,
                            Played = 38,
                            Points = 72,
                            Position = 2,
                            SeasonID = 4,
                            TeamID = 15,
                            Won = 21
                        },
                        new
                        {
                            ID = 63,
                            Drawn = 12,
                            GoalsAgainst = 29,
                            GoalsFor = 51,
                            Lost = 7,
                            Played = 38,
                            Points = 69,
                            Position = 3,
                            SeasonID = 4,
                            TeamID = 20,
                            Won = 19
                        },
                        new
                        {
                            ID = 64,
                            Drawn = 12,
                            GoalsAgainst = 27,
                            GoalsFor = 48,
                            Lost = 8,
                            Played = 38,
                            Points = 66,
                            Position = 4,
                            SeasonID = 4,
                            TeamID = 19,
                            Won = 18
                        },
                        new
                        {
                            ID = 65,
                            Drawn = 15,
                            GoalsAgainst = 34,
                            GoalsFor = 46,
                            Lost = 7,
                            Played = 38,
                            Points = 63,
                            Position = 5,
                            SeasonID = 4,
                            TeamID = 27,
                            Won = 16
                        },
                        new
                        {
                            ID = 66,
                            Drawn = 8,
                            GoalsAgainst = 43,
                            GoalsFor = 56,
                            Lost = 13,
                            Played = 38,
                            Points = 59,
                            Position = 6,
                            SeasonID = 4,
                            TeamID = 3,
                            Won = 17
                        },
                        new
                        {
                            ID = 67,
                            Drawn = 9,
                            GoalsAgainst = 37,
                            GoalsFor = 54,
                            Lost = 13,
                            Played = 38,
                            Points = 57,
                            Position = 7,
                            SeasonID = 4,
                            TeamID = 4,
                            Won = 16
                        },
                        new
                        {
                            ID = 68,
                            Drawn = 11,
                            GoalsAgainst = 34,
                            GoalsFor = 34,
                            Lost = 13,
                            Played = 38,
                            Points = 53,
                            Position = 8,
                            SeasonID = 4,
                            TeamID = 12,
                            Won = 14
                        },
                        new
                        {
                            ID = 69,
                            Drawn = 12,
                            GoalsAgainst = 46,
                            GoalsFor = 38,
                            Lost = 13,
                            Played = 38,
                            Points = 51,
                            Position = 9,
                            SeasonID = 4,
                            TeamID = 7,
                            Won = 13
                        },
                        new
                        {
                            ID = 70,
                            Drawn = 11,
                            GoalsAgainst = 40,
                            GoalsFor = 46,
                            Lost = 14,
                            Played = 38,
                            Points = 50,
                            Position = 10,
                            SeasonID = 4,
                            TeamID = 26,
                            Won = 13
                        },
                        new
                        {
                            ID = 71,
                            Drawn = 12,
                            GoalsAgainst = 41,
                            GoalsFor = 39,
                            Lost = 14,
                            Played = 38,
                            Points = 48,
                            Position = 11,
                            SeasonID = 4,
                            TeamID = 6,
                            Won = 12
                        },
                        new
                        {
                            ID = 72,
                            Drawn = 9,
                            GoalsAgainst = 46,
                            GoalsFor = 32,
                            Lost = 17,
                            Played = 38,
                            Points = 45,
                            Position = 12,
                            SeasonID = 4,
                            TeamID = 16,
                            Won = 12
                        },
                        new
                        {
                            ID = 73,
                            Drawn = 11,
                            GoalsAgainst = 35,
                            GoalsFor = 34,
                            Lost = 16,
                            Played = 38,
                            Points = 44,
                            Position = 13,
                            SeasonID = 4,
                            TeamID = 10,
                            Won = 11
                        },
                        new
                        {
                            ID = 74,
                            Drawn = 11,
                            GoalsAgainst = 50,
                            GoalsFor = 34,
                            Lost = 16,
                            Played = 38,
                            Points = 44,
                            Position = 14,
                            SeasonID = 4,
                            TeamID = 9,
                            Won = 11
                        },
                        new
                        {
                            ID = 75,
                            Drawn = 14,
                            GoalsAgainst = 38,
                            GoalsFor = 32,
                            Lost = 14,
                            Played = 38,
                            Points = 44,
                            Position = 15,
                            SeasonID = 4,
                            TeamID = 8,
                            Won = 10
                        },
                        new
                        {
                            ID = 76,
                            Drawn = 13,
                            GoalsAgainst = 48,
                            GoalsFor = 41,
                            Lost = 15,
                            Played = 38,
                            Points = 43,
                            Position = 16,
                            SeasonID = 4,
                            TeamID = 29,
                            Won = 10
                        },
                        new
                        {
                            ID = 77,
                            Drawn = 10,
                            GoalsAgainst = 47,
                            GoalsFor = 30,
                            Lost = 18,
                            Played = 38,
                            Points = 40,
                            Position = 17,
                            SeasonID = 4,
                            TeamID = 1,
                            Won = 10
                        },
                        new
                        {
                            ID = 78,
                            Drawn = 9,
                            GoalsAgainst = 57,
                            GoalsFor = 35,
                            Lost = 18,
                            Played = 38,
                            Points = 39,
                            Position = 18,
                            SeasonID = 4,
                            TeamID = 28,
                            Won = 11
                        },
                        new
                        {
                            ID = 79,
                            Drawn = 10,
                            GoalsAgainst = 63,
                            GoalsFor = 36,
                            Lost = 19,
                            Played = 38,
                            Points = 37,
                            Position = 19,
                            SeasonID = 4,
                            TeamID = 30,
                            Won = 9
                        },
                        new
                        {
                            ID = 80,
                            Drawn = 11,
                            GoalsAgainst = 57,
                            GoalsFor = 18,
                            Lost = 23,
                            Played = 38,
                            Points = 23,
                            Position = 20,
                            SeasonID = 4,
                            TeamID = 23,
                            Won = 4
                        },
                        new
                        {
                            ID = 81,
                            Drawn = 6,
                            GoalsAgainst = 37,
                            GoalsFor = 86,
                            Lost = 4,
                            Played = 38,
                            Points = 90,
                            Position = 1,
                            SeasonID = 5,
                            TeamID = 15,
                            Won = 28
                        },
                        new
                        {
                            ID = 82,
                            Drawn = 8,
                            GoalsAgainst = 33,
                            GoalsFor = 60,
                            Lost = 8,
                            Played = 38,
                            Points = 74,
                            Position = 2,
                            SeasonID = 5,
                            TeamID = 26,
                            Won = 22
                        },
                        new
                        {
                            ID = 83,
                            Drawn = 11,
                            GoalsAgainst = 32,
                            GoalsFor = 61,
                            Lost = 6,
                            Played = 38,
                            Points = 74,
                            Position = 3,
                            SeasonID = 5,
                            TeamID = 22,
                            Won = 21
                        },
                        new
                        {
                            ID = 84,
                            Drawn = 8,
                            GoalsAgainst = 39,
                            GoalsFor = 64,
                            Lost = 11,
                            Played = 38,
                            Points = 65,
                            Position = 4,
                            SeasonID = 5,
                            TeamID = 19,
                            Won = 19
                        },
                        new
                        {
                            ID = 85,
                            Drawn = 10,
                            GoalsAgainst = 32,
                            GoalsFor = 51,
                            Lost = 10,
                            Played = 38,
                            Points = 64,
                            Position = 5,
                            SeasonID = 5,
                            TeamID = 4,
                            Won = 18
                        },
                        new
                        {
                            ID = 86,
                            Drawn = 12,
                            GoalsAgainst = 30,
                            GoalsFor = 39,
                            Lost = 9,
                            Played = 38,
                            Points = 63,
                            Position = 6,
                            SeasonID = 5,
                            TeamID = 27,
                            Won = 17
                        },
                        new
                        {
                            ID = 87,
                            Drawn = 9,
                            GoalsAgainst = 39,
                            GoalsFor = 44,
                            Lost = 13,
                            Played = 38,
                            Points = 57,
                            Position = 7,
                            SeasonID = 5,
                            TeamID = 20,
                            Won = 16
                        },
                        new
                        {
                            ID = 88,
                            Drawn = 14,
                            GoalsAgainst = 34,
                            GoalsFor = 42,
                            Lost = 10,
                            Played = 38,
                            Points = 56,
                            Position = 8,
                            SeasonID = 5,
                            TeamID = 10,
                            Won = 14
                        },
                        new
                        {
                            ID = 89,
                            Drawn = 8,
                            GoalsAgainst = 49,
                            GoalsFor = 50,
                            Lost = 15,
                            Played = 38,
                            Points = 53,
                            Position = 9,
                            SeasonID = 5,
                            TeamID = 17,
                            Won = 15
                        },
                        new
                        {
                            ID = 90,
                            Drawn = 7,
                            GoalsAgainst = 64,
                            GoalsFor = 46,
                            Lost = 16,
                            Played = 38,
                            Points = 52,
                            Position = 10,
                            SeasonID = 5,
                            TeamID = 18,
                            Won = 15
                        },
                        new
                        {
                            ID = 91,
                            Drawn = 13,
                            GoalsAgainst = 43,
                            GoalsFor = 44,
                            Lost = 13,
                            Played = 38,
                            Points = 49,
                            Position = 11,
                            SeasonID = 5,
                            TeamID = 6,
                            Won = 12
                        },
                        new
                        {
                            ID = 92,
                            Drawn = 13,
                            GoalsAgainst = 45,
                            GoalsFor = 39,
                            Lost = 13,
                            Played = 38,
                            Points = 49,
                            Position = 12,
                            SeasonID = 5,
                            TeamID = 29,
                            Won = 12
                        },
                        new
                        {
                            ID = 93,
                            Drawn = 9,
                            GoalsAgainst = 49,
                            GoalsFor = 45,
                            Lost = 16,
                            Played = 38,
                            Points = 48,
                            Position = 13,
                            SeasonID = 5,
                            TeamID = 3,
                            Won = 13
                        },
                        new
                        {
                            ID = 94,
                            Drawn = 10,
                            GoalsAgainst = 46,
                            GoalsFor = 38,
                            Lost = 16,
                            Played = 38,
                            Points = 46,
                            Position = 14,
                            SeasonID = 5,
                            TeamID = 16,
                            Won = 12
                        },
                        new
                        {
                            ID = 95,
                            Drawn = 4,
                            GoalsAgainst = 45,
                            GoalsFor = 31,
                            Lost = 21,
                            Played = 38,
                            Points = 43,
                            Position = 15,
                            SeasonID = 5,
                            TeamID = 7,
                            Won = 13
                        },
                        new
                        {
                            ID = 96,
                            Drawn = 9,
                            GoalsAgainst = 41,
                            GoalsFor = 36,
                            Lost = 19,
                            Played = 38,
                            Points = 39,
                            Position = 16,
                            SeasonID = 5,
                            TeamID = 8,
                            Won = 10
                        },
                        new
                        {
                            ID = 97,
                            Drawn = 15,
                            GoalsAgainst = 46,
                            GoalsFor = 27,
                            Lost = 16,
                            Played = 38,
                            Points = 36,
                            Position = 17,
                            SeasonID = 5,
                            TeamID = 12,
                            Won = 7
                        },
                        new
                        {
                            ID = 98,
                            Drawn = 8,
                            GoalsAgainst = 58,
                            GoalsFor = 24,
                            Lost = 22,
                            Played = 38,
                            Points = 32,
                            Position = 18,
                            SeasonID = 5,
                            TeamID = 13,
                            Won = 8
                        },
                        new
                        {
                            ID = 99,
                            Drawn = 11,
                            GoalsAgainst = 52,
                            GoalsFor = 31,
                            Lost = 20,
                            Played = 38,
                            Points = 32,
                            Position = 19,
                            SeasonID = 5,
                            TeamID = 9,
                            Won = 7
                        },
                        new
                        {
                            ID = 100,
                            Drawn = 11,
                            GoalsAgainst = 62,
                            GoalsFor = 18,
                            Lost = 24,
                            Played = 38,
                            Points = 20,
                            Position = 20,
                            SeasonID = 5,
                            TeamID = 5,
                            Won = 3
                        });
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions_Seasons", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompetitionID = 1,
                            Year = 2015
                        },
                        new
                        {
                            ID = 2,
                            CompetitionID = 1,
                            Year = 2016
                        },
                        new
                        {
                            ID = 3,
                            CompetitionID = 1,
                            Year = 2017
                        },
                        new
                        {
                            ID = 4,
                            CompetitionID = 1,
                            Year = 2018
                        },
                        new
                        {
                            ID = 5,
                            CompetitionID = 1,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.States", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "AC",
                            Name = "Acre"
                        },
                        new
                        {
                            ID = 2,
                            Code = "AL",
                            Name = "Alagoas"
                        },
                        new
                        {
                            ID = 3,
                            Code = "AP",
                            Name = "Amapá"
                        },
                        new
                        {
                            ID = 4,
                            Code = "AM",
                            Name = "Amazonas"
                        },
                        new
                        {
                            ID = 5,
                            Code = "BA",
                            Name = "Bahia"
                        },
                        new
                        {
                            ID = 6,
                            Code = "CE",
                            Name = "Ceará"
                        },
                        new
                        {
                            ID = 7,
                            Code = "DF",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            ID = 8,
                            Code = "ES",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            ID = 9,
                            Code = "GO",
                            Name = "Goiás"
                        },
                        new
                        {
                            ID = 10,
                            Code = "MA",
                            Name = "Maranhão"
                        },
                        new
                        {
                            ID = 11,
                            Code = "MT",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            ID = 12,
                            Code = "MS",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            ID = 13,
                            Code = "MG",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            ID = 14,
                            Code = "PA",
                            Name = "Pará"
                        },
                        new
                        {
                            ID = 15,
                            Code = "PB",
                            Name = "Paraíba"
                        },
                        new
                        {
                            ID = 16,
                            Code = "PR",
                            Name = "Paraná"
                        },
                        new
                        {
                            ID = 17,
                            Code = "PE",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            ID = 18,
                            Code = "PI",
                            Name = "Piauí"
                        },
                        new
                        {
                            ID = 19,
                            Code = "RJ",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            ID = 20,
                            Code = "RN",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            ID = 21,
                            Code = "RS",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            ID = 22,
                            Code = "RO",
                            Name = "Rondônia"
                        },
                        new
                        {
                            ID = 23,
                            Code = "RR",
                            Name = "Roraima"
                        },
                        new
                        {
                            ID = 24,
                            Code = "SC",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            ID = 25,
                            Code = "SP",
                            Name = "São Paulo"
                        },
                        new
                        {
                            ID = 26,
                            Code = "SE",
                            Name = "Sergipe"
                        },
                        new
                        {
                            ID = 27,
                            Code = "TO",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Teams", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("StateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "América Mineiro",
                            StateID = 13
                        },
                        new
                        {
                            ID = 2,
                            Name = "Atlético Goiás",
                            StateID = 9
                        },
                        new
                        {
                            ID = 3,
                            Name = "Atlético MG",
                            StateID = 13
                        },
                        new
                        {
                            ID = 4,
                            Name = "Atlético PR",
                            StateID = 16
                        },
                        new
                        {
                            ID = 5,
                            Name = "Avaí",
                            StateID = 24
                        },
                        new
                        {
                            ID = 6,
                            Name = "Bahia",
                            StateID = 5
                        },
                        new
                        {
                            ID = 7,
                            Name = "Botafogo",
                            StateID = 19
                        },
                        new
                        {
                            ID = 8,
                            Name = "Ceará",
                            StateID = 6
                        },
                        new
                        {
                            ID = 9,
                            Name = "Chapecoense",
                            StateID = 24
                        },
                        new
                        {
                            ID = 10,
                            Name = "Corinthians",
                            StateID = 25
                        },
                        new
                        {
                            ID = 11,
                            Name = "Coritiba",
                            StateID = 16
                        },
                        new
                        {
                            ID = 12,
                            Name = "Cruzeiro",
                            StateID = 13
                        },
                        new
                        {
                            ID = 13,
                            Name = "CSA",
                            StateID = 2
                        },
                        new
                        {
                            ID = 14,
                            Name = "Figueirense",
                            StateID = 24
                        },
                        new
                        {
                            ID = 15,
                            Name = "Flamengo",
                            StateID = 19
                        },
                        new
                        {
                            ID = 16,
                            Name = "Fluminense",
                            StateID = 19
                        },
                        new
                        {
                            ID = 17,
                            Name = "Fortaleza",
                            StateID = 6
                        },
                        new
                        {
                            ID = 18,
                            Name = "Goiás",
                            StateID = 9
                        },
                        new
                        {
                            ID = 19,
                            Name = "Grêmio",
                            StateID = 21
                        },
                        new
                        {
                            ID = 20,
                            Name = "Internacional",
                            StateID = 21
                        },
                        new
                        {
                            ID = 21,
                            Name = "Joinvile",
                            StateID = 24
                        },
                        new
                        {
                            ID = 22,
                            Name = "Palmeiras",
                            StateID = 25
                        },
                        new
                        {
                            ID = 23,
                            Name = "Paraná",
                            StateID = 16
                        },
                        new
                        {
                            ID = 24,
                            Name = "Ponte Preta",
                            StateID = 25
                        },
                        new
                        {
                            ID = 25,
                            Name = "Santa Cruz",
                            StateID = 17
                        },
                        new
                        {
                            ID = 26,
                            Name = "Santos",
                            StateID = 25
                        },
                        new
                        {
                            ID = 27,
                            Name = "São Paulo",
                            StateID = 25
                        },
                        new
                        {
                            ID = 28,
                            Name = "Sport",
                            StateID = 17
                        },
                        new
                        {
                            ID = 29,
                            Name = "Vasco da Gama",
                            StateID = 19
                        },
                        new
                        {
                            ID = 30,
                            Name = "Vitória",
                            StateID = 5
                        });
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions_ResultTable", b =>
                {
                    b.HasOne("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions_Seasons", "Season")
                        .WithMany("Results")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrazilianFootballLeague.DataAccess.BusinessObjects.Teams", "Team")
                        .WithMany("Results")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions_Seasons", b =>
                {
                    b.HasOne("BrazilianFootballLeague.DataAccess.BusinessObjects.Competitions", "Competition")
                        .WithMany("Seasons")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrazilianFootballLeague.DataAccess.BusinessObjects.Teams", b =>
                {
                    b.HasOne("BrazilianFootballLeague.DataAccess.BusinessObjects.States", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
